### ISSUE TITLE
ImportError: DLL load failed: The specified module cannot be found.

### ISSUE THREAD

**Issue by air006600** [SysCV/transfiner#46]
(transfiner) D:\python\new_maskrcnn\transfiner-main\transfiner\tools>python train_net.py
Traceback (most recent call last):
  File "train_net.py", line 27, in <module>
    from detectron2.data import MetadataCatalog
  File "D:\python\new_maskrcnn\transfiner-main\transfiner\tools\detectron2\data\__init__.py", line 2, in <module>
    from . import transforms  # isort:skip
  File "D:\python\new_maskrcnn\transfiner-main\transfiner\tools\detectron2\data\transforms\__init__.py", line 4, in <module>
    from .transform import *
  File "D:\python\new_maskrcnn\transfiner-main\transfiner\tools\detectron2\data\transforms\transform.py", line 19, in <module>
    from PIL import Image
  File "C:\Users\daskv\Miniconda3\envs\transfiner\lib\site-packages\PIL\Image.py", line 100, in <module>
    from . import _imaging as core
ImportError: DLL load failed: The specified module cannot be found.

Another question: is this usable on Windows?

My environment:
antlr-python-runtime      4.9.3              pyhd8ed1ab_1    conda-forge
blas                      1.0                         mkl
ca-certificates           2022.12.7            h5b45459_0    conda-forge
certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
cloudpickle               2.2.1              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
cudatoolkit               11.0.221             h74a9793_0
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cython                    0.29.33                  pypi_0    pypi
dataclasses               0.8                pyhc8e2a94_3    conda-forge
fonttools                 4.38.0                   pypi_0    pypi
freetype                  2.12.1               ha860e81_0
fvcore                    0.1.5.post20221221    pyhd8ed1ab_0    conda-forge
imageio                   2.26.1                   pypi_0    pypi
imgviz                    1.7.2                    pypi_0    pypi
intel-openmp              2021.4.0          haa95532_3556
iopath                    0.1.9              pyhd8ed1ab_0    conda-forge
jpeg                      9b                   hb83a4c4_2
kiwisolver                1.4.4                    pypi_0    pypi
kornia                    0.5.11                   pypi_0    pypi
labelme                   5.1.1                    pypi_0    pypi
lerc                      3.0                  hd77b12b_0
libdeflate                1.17                 h2bbff1b_0
libpng                    1.6.39               h8cc25b3_0
libtiff                   4.5.0                h8a3f274_0
libuv                     1.44.2               h2bbff1b_0
libwebp                   1.2.4                h2bbff1b_0
libwebp-base              1.2.4                h2bbff1b_1
lz4-c                     1.9.4                h2bbff1b_0
matplotlib                3.5.3                    pypi_0    pypi
matplotlib-base           3.4.3            py37h4a79c79_2    conda-forge
mkl                       2021.4.0           haa95532_640
mkl-service               2.4.0            py37h2bbff1b_0
mkl_fft                   1.3.1            py37h277e83a_0
mkl_random                1.2.2            py37hf11a4ad_0
natsort                   8.3.1                    pypi_0    pypi
networkx                  2.6.3                    pypi_0    pypi
ninja                     1.11.1                   pypi_0    pypi
ninja-base                1.10.2               h6d14046_5
numpy                     1.21.5           py37h7a0a035_3
numpy-base                1.21.5           py37hca35cd5_3
omegaconf                 2.3.0              pyhd8ed1ab_0    conda-forge
opencv-python             4.4.0.40                 pypi_0    pypi
openssl                   1.1.1t               h2bbff1b_0
packaging                 23.0                     pypi_0    pypi
pillow                    9.4.0                    pypi_0    pypi
pip                       22.3.1           py37haa95532_0
portalocker               1.4.0                      py_0    conda-forge
pycocotools               2.0.4            py37h3a130e4_1    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyqt5                     5.15.9                   pypi_0    pypi
pyqt5-qt5                 5.15.2                   pypi_0    pypi
pyqt5-sip                 12.11.1                  pypi_0    pypi
python                    3.7.16               h6244533_0
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.7                     2_cp37m    conda-forge
pytorch                   1.7.1           py3.7_cuda110_cudnn8_0    pytorch
pywavelets                1.3.0                    pypi_0    pypi
pywin32                   305              py37h2bbff1b_0    anaconda
pyyaml                    6.0              py37hcc03f2d_4    conda-forge
qtpy                      2.3.0                    pypi_0    pypi
scikit-image              0.19.3                   pypi_0    pypi
scipy                     1.7.3                    pypi_0    pypi
setuptools                65.6.3           py37haa95532_0
six                       1.16.0             pyhd3eb1b0_1
sqlite                    3.41.1               h2bbff1b_0
tabulate                  0.9.0              pyhd8ed1ab_1    conda-forge
termcolor                 2.2.0              pyhd8ed1ab_0    conda-forge
tifffile                  2021.11.2                pypi_0    pypi
tk                        8.6.12               h2bbff1b_0
torchaudio                0.7.2                      py37    pytorch
torchvision               0.8.2                py37_cu110    pytorch
tornado                   6.2              py37hcc03f2d_0    conda-forge
tqdm                      4.65.0             pyhd8ed1ab_1    conda-forge
typing-extensions         4.5.0                    pypi_0    pypi
typing_extensions         4.3.0            py37haa95532_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wheel                     0.38.4           py37haa95532_0
wincertstore              0.2              py37haa95532_2
xz                        5.2.10               h8cc25b3_1
yacs                      0.1.8              pyhd8ed1ab_0    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
zlib                      1.2.13               h8cc25b3_0
zstd                      1.5.2                h19a0ad4_0

**Comment by lkeab** [comment]
Hi it seems your error is in the PIL package. Our project can be used on window as we build mask transfiner on detectron2. And detectron2 is supported in windows platform. see [link](https://medium.com/@yogeshkumarpilli/how-to-install-detectron2-on-windows-10-or-11-2021-aug-with-the-latest-build-v0-5-c7333909676f) and [link](https://github.com/DGMaxime/detectron2-windows/blob/master/INSTALL.md)
