### ISSUE TITLE
compile fail

### ISSUE THREAD

**Issue by paul-ml75** [SysCV/transfiner#48]
Hi everyone,

i'm on windows 11, and i'm having this error when i follow the Step-by-step guide (after cd transfiner/
python3 setup.py build develop):

> FAILED: C:/Users/Shadow/transfiner/build/temp.win-amd64-cpython-37/Release/Users/Shadow/transfiner/detectron2/layers/csrc/nms_rotated/nms_rotated_cuda.obj
> C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\bin\nvcc --use-local-env -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -DWITH_CUDA -IC:\Users\Shadow\transfiner\detectron2\layers\csrc -IC:\ProgramData\anaconda3\envs\transfiner\lib\site-packages\torch\include -IC:\ProgramData\anaconda3\envs\transfiner\lib\site-packages\torch\include\torch\csrc\api\include -IC:\ProgramData\anaconda3\envs\transfiner\lib\site-packages\torch\include\TH -IC:\ProgramData\anaconda3\envs\transfiner\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\include" -IC:\ProgramData\anaconda3\envs\transfiner\include -IC:\ProgramData\anaconda3\envs\transfiner\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\cppwinrt" -c C:\Users\Shadow\transfiner\detectron2\layers\csrc\nms_rotated\nms_rotated_cuda.cu -o C:\Users\Shadow\transfiner\build\temp.win-amd64-cpython-37\Release\Users\Shadow\transfiner\detectron2\layers\csrc\nms_rotated\nms_rotated_cuda.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=sm_86
> nvcc fatal   : Unsupported gpu architecture 'compute_86'
> ninja: build stopped: subcommand failed.
> Traceback (most recent call last):
>   File "C:\ProgramData\anaconda3\envs\transfiner\lib\site-packages\torch\utils\cpp_extension.py", line 1539, in _run_ninja_build
>     env=env)
>   File "C:\ProgramData\anaconda3\envs\transfiner\lib\subprocess.py", line 512, in run
>     output=stdout, stderr=stderr)
> subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "setup.py", line 207, in <module>
>     cmdclass={"build_ext": torch.utils.cpp_extension.BuildExtension},
>   File "C:\ProgramData\anaconda3\envs\transfiner\lib\site-packages\setuptools\__init__.py", line 87, in setup
>     return distutils.core.setup(**attrs)
>   File "C:\ProgramData\anaconda3\envs\transfiner\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
>     return run_commands(dist)
>   File "C:\ProgramData\anaconda3\envs\transfiner\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
>     dist.run_commands()
>   File "C:\ProgramData\anaconda3\envs\transfiner\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
>     self.run_command(cmd)
>   File "C:\ProgramData\anaconda3\envs\transfiner\lib\site-packages\setuptools\dist.py", line 1208, in run_command
>     super().run_command(command)
>   File "C:\ProgramData\anaconda3\envs\transfiner\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
>     cmd_obj.run()
>   File "C:\ProgramData\anaconda3\envs\transfiner\lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
>     self.run_command(cmd_name)
>   File "C:\ProgramData\anaconda3\envs\transfiner\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
>     self.distribution.run_command(command)
>   File "C:\ProgramData\anaconda3\envs\transfiner\lib\site-packages\setuptools\dist.py", line 1208, in run_command
>     super().run_command(command)
>   File "C:\ProgramData\anaconda3\envs\transfiner\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
>     cmd_obj.run()
>   File "C:\ProgramData\anaconda3\envs\transfiner\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
>     _build_ext.run(self)
>   File "C:\ProgramData\anaconda3\envs\transfiner\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
>     _build_ext.build_ext.run(self)
>   File "C:\ProgramData\anaconda3\envs\transfiner\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 346, in run
>     self.build_extensions()
>   File "C:\ProgramData\anaconda3\envs\transfiner\lib\site-packages\torch\utils\cpp_extension.py", line 670, in build_extensions
>     build_ext.build_extensions(self)
>   File "C:\ProgramData\anaconda3\envs\transfiner\lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
>     _build_ext.build_ext.build_extensions(self)
>   File "C:\ProgramData\anaconda3\envs\transfiner\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 468, in build_extensions
>     self._build_extensions_serial()
>   File "C:\ProgramData\anaconda3\envs\transfiner\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 494, in _build_extensions_serial
>     self.build_extension(ext)
>   File "C:\ProgramData\anaconda3\envs\transfiner\lib\site-packages\setuptools\command\build_ext.py", line 246, in build_extension
>     _build_ext.build_extension(self, ext)
>   File "C:\ProgramData\anaconda3\envs\transfiner\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 556, in build_extension
>     depends=ext.depends,
>   File "C:\ProgramData\anaconda3\envs\transfiner\lib\site-packages\torch\utils\cpp_extension.py", line 652, in win_wrap_ninja_compile
>     with_cuda=with_cuda)
>   File "C:\ProgramData\anaconda3\envs\transfiner\lib\site-packages\torch\utils\cpp_extension.py", line 1255, in _write_ninja_file_and_compile_objects
>     error_prefix='Error compiling objects for extension')
>   File "C:\ProgramData\anaconda3\envs\transfiner\lib\site-packages\torch\utils\cpp_extension.py", line 1555, in _run_ninja_build
>     raise RuntimeError(message) from e
> RuntimeError: Error compiling objects for extension

do you have any idea what could cause this error?

kind regards,

Paul

**Comment by lkeab** [comment]
Hi, our project can be used on window as we build mask transfiner on detectron2. And detectron2 is supported in windows platform (but I have not tried it on windows). I think this error is caused because of wrong/incomplete detectron2 installation. see [link](https://medium.com/@yogeshkumarpilli/how-to-install-detectron2-on-windows-10-or-11-2021-aug-with-the-latest-build-v0-5-c7333909676f) and [link](https://github.com/DGMaxime/detectron2-windows/blob/master/INSTALL.md) to follow their step-by-step instructions.
